AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "An example AWS stack with a Rust Lambda runtime"

Resources:
  TestRustLambda:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: TestRustLambda
      Handler: handlers::test::handler # qualified function name
      Runtime: provided
      MemorySize: 128
      CodeUri: .
  AnotherLambda:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: AnotherLambda
      Handler: handlers::test::handler # qualified function name
      Runtime: provided
      MemorySize: 128
      CodeUri: .
